Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds_ingested = act.io.read_netcdf('/Volumes/T7/data/DL_ingested/crocus-neiu-dlvpt-a1-202308020000.nc')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m ds_ingested [38;5;241m=[39m [43mact[49m[38;5;241;43m.[39;49m[43mio[49m[38;5;241;43m.[39;49m[43mread_netcdf[49m([38;5;124m'[39m[38;5;124m/Volumes/T7/data/DL_ingested/crocus-neiu-dlvpt-a1-202308020000.nc[39m[38;5;124m'[39m)

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/lazy_loader/__init__.py:94[0m, in [0;36mattach.<locals>.__getattr__[0;34m(name)[0m
[1;32m     92[0m     [38;5;28;01mreturn[39;00m attr
[1;32m     93[0m [38;5;28;01melse[39;00m:
[0;32m---> 94[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo [39m[38;5;132;01m{[39;00mpackage_name[38;5;132;01m}[39;00m[38;5;124m attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mAttributeError[0m: No act.io attribute read_netcdf

