Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import act
import glob
import matplotlib.pyplot as plt
import matplotlib

files = glob.glob('../../data/ceilometer/sgp*')

ds = act.io.read_netcdf(files)

# apply range correction
ds = act.corrections.correct_ceil(ds)

ds.attrs['datastream'] = 'ceilometer.b1'

# variables=['p_pol', 'x_pol', 'linear_depol_ratio']

variables = ['backscatter', 'first_cbh']

for variable in variables:
    display = act.plotting.TimeSeriesDisplay(ds, figsize=(8,4))
    if variable == 'backscatter':
        display.plot(variable,
                     cmap='rainbow',
                     vmin=0,
                     vmax=4,
                     y_rng=(0, ds.range.max().values))
    else:
        display.plot(variable,
                     cmap='rainbow',
                     y_rng=(0, ds.range.max().values))

    plt.show()
    plt.close()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[1], line 8[0m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m
[1;32m      6[0m files [38;5;241m=[39m glob[38;5;241m.[39mglob([38;5;124m'[39m[38;5;124m../../data/ceilometer/sgp*[39m[38;5;124m'[39m)
[0;32m----> 8[0m ds [38;5;241m=[39m [43mact[49m[38;5;241;43m.[39;49m[43mio[49m[38;5;241;43m.[39;49m[43mread_netcdf[49m(files)
[1;32m     10[0m [38;5;66;03m# apply range correction[39;00m
[1;32m     11[0m ds [38;5;241m=[39m act[38;5;241m.[39mcorrections[38;5;241m.[39mcorrect_ceil(ds)

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/lazy_loader/__init__.py:89[0m, in [0;36mattach.<locals>.__getattr__[0;34m(name)[0m
[1;32m     87[0m     [38;5;28;01mreturn[39;00m attr
[1;32m     88[0m [38;5;28;01melse[39;00m:
[0;32m---> 89[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo [39m[38;5;132;01m{[39;00mpackage_name[38;5;132;01m}[39;00m[38;5;124m attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mAttributeError[0m: No act.io attribute read_netcdf

